### PR TITLE
podnetwork: Support CNI plugins like PTP and GKE 

### LINKED ISSUE #1909: agent-protocol-forwarder failing to bootstrap because of routes conflicting
I'm provisioning a [new provider](https://github.com/beraldoleal/cloud-api-adaptor/tree/mainplusgcp/src/cloud-providers/gcp) (GCP/GKE) and for some reason on the PodVM the agent-protocol-forwarder is having some issues to bootstrap.

After realizing the forwarder was not starting due to vxlan conflicts, I deleted the vxlan manually and executed the following tests:

Here is the network on the PodVM before:

```
[root@fedora ~]# ip netns exec podns ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host proto kernel_lo
       valid_lft forever preferred_lft forever
5: veth2@if4: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether 56:e0:a7:64:cd:11 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet6 fe80::54e0:a7ff:fe64:cd11/64 scope link proto kernel_ll
       valid_lft forever preferred_lft forever

[root@fedora ~]# ip netns exec podns ip r
169.254.169.254 dev veth2 scope link
```

Note that there is no vxlan interface and no routes at this point. Then I start the agent-protocol-forwarder:

```
/usr/local/bin/agent-protocol-forwarder -kata-agent-namespace /run/netns/podns -kata-agent-socket /run/kata-containers/agent.sock $TLS_OPTIONS $OPTIONS

agent-protocol-forwarder version v0.8.2-dev
  commit: 277e518665c96e5df62b3e63b2e9dae3ac5bf587-dirty
  go: go1.21.11
/usr/local/bin/agent-protocol-forwarder: error running a service *forwarder.daemon: failed to set up pod network: failed to set up tunnel "vxlan": failed to add a route to 10.120.1.0/24 via 10.120.1.1 on pod network namespace /run/netns/podns: failed to create a route (table: 0, dest: 10.120.1.0/24, gw: 10.120.1.1) with flags 0: file exists
```

It is actually complaining the route already exists, but wait, there was no route before on the podns, but If check now:

```
# ip netns exec podns ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host proto kernel_lo
       valid_lft forever preferred_lft forever
5: veth2@if4: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether 56:e0:a7:64:cd:11 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet6 fe80::54e0:a7ff:fe64:cd11/64 scope link proto kernel_ll
       valid_lft forever preferred_lft forever
13: vxlan-peerpods@if13: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue state UNKNOWN group default
    link/ether 66:a2:52:de:5d:35 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 10.120.1.13/24 brd 10.120.1.255 scope global vxlan-peerpods
       valid_lft forever preferred_lft forever
    inet6 fe80::64a2:52ff:fede:5d35/64 scope link proto kernel_ll
       valid_lft forever preferred_lft forever

[root@fedora ~]# ip netns exec podns ip r
default via 10.120.1.1 dev vxlan-peerpods
10.120.1.0/24 dev vxlan-peerpods proto kernel scope link src 10.120.1.13
10.120.1.1 dev vxlan-peerpods scope link
169.254.169.254 dev veth2 scope link
```

GKE network is currently a "default" VPC with one subnet for each region (also called "default"). Both VMs and GKE nodes are using this default VPC. What I tried so far:
- Changed the VXLAN_PORT as suggested by @bpradipt
- Tried GKE cluster with -no-alias-ip
- Investigated the possibility of using Calico, but its not supported by GKE to change the CNI plugin

Here is also the `daemon.json`:

```
    "pod-network": {
        "podip": "10.84.0.9/24",
        "pod-hw-addr": "ba:47:d0:73:da:b9",
        "interface": "eth0",
        "worker-node-ip": "10.138.0.9/32",
        "tunnel-type": "vxlan",
        "routes": [
            {
                "Dst": "0.0.0.0/0",
                "GW": "10.84.0.1",
                "Dev": "eth0"
            },
            {
                "Dst": "10.84.0.0/24",
                "GW": "10.84.0.1",
                "Dev": "eth0"
            },
            {
                "Dst": "10.84.0.1/32",
                "GW": "",
                "Dev": "eth0"
            }
        ],
        "mtu": 1460,
        "index": 0,
        "vxlan-port": 4790,
        "vxlan-id": 555000,
        "dedicated": false
    },
    "pod-namespace": "coco-pp-e2e-test-5fa2ec1f",
    "pod-name": "simple-test",
```

And detailed interfaces for both PodVM and podns:

```
[root@fedora ~]# ip -d a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00 promiscuity 0 allmulti 0 minmtu 0 maxmtu 0 numtxqueues 1 numrxqueues 1 gso_max_size 65536 gso_max_segs 65535 tso_max_size 524280 tso_max_segs 65535 gro_max_size 65536 gso_ipv4_max_size 65536 gro_ipv4_max_size 65536 
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host noprefixroute 
       valid_lft forever preferred_lft forever
2: ens4: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 42:01:0a:8a:00:0d brd ff:ff:ff:ff:ff:ff promiscuity 0 allmulti 0 minmtu 68 maxmtu 65535 numtxqueues 1 numrxqueues 1 gso_max_size 65536 gso_max_segs 65535 tso_max_size 65536 tso_max_segs 65535 gro_max_size 65536 gso_ipv4_max_size 65536 gro_ipv4_max_size 65536 parentbus virtio parentdev virtio1 
    altname enp0s4
    inet 10.138.0.13/32 metric 1024 scope global dynamic ens4
       valid_lft 3444sec preferred_lft 3444sec
    inet6 fe80::4001:aff:fe8a:d/64 scope link proto kernel_ll 
       valid_lft forever preferred_lft forever
4: veth1@if5: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether 06:e1:0f:21:53:2a brd ff:ff:ff:ff:ff:ff link-netns podns promiscuity 0 allmulti 0 minmtu 68 maxmtu 65535 
    veth numtxqueues 1 numrxqueues 1 gso_max_size 65536 gso_max_segs 65535 tso_max_size 524280 tso_max_segs 65535 gro_max_size 65536 gso_ipv4_max_size 65536 gro_ipv4_max_size 65536 
    inet 169.254.99.99/32 scope global veth1
       valid_lft forever preferred_lft forever
    inet6 fe80::4e1:fff:fe21:532a/64 scope link proto kernel_ll 
       valid_lft forever preferred_lft forever
````

```
[root@fedora ~]# ip netns exec podns ip -d a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00 promiscuity 0 allmulti 0 minmtu 0 maxmtu 0 numtxqueues 1 numrxqueues 1 gso_max_size 65536 gso_max_segs 65535 tso_max_size 524280 tso_max_segs 65535 gro_max_size 65536 gso_ipv4_max_size 65536 gro_ipv4_max_size 65536 
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host proto kernel_lo 
       valid_lft forever preferred_lft forever
3: vxlan-peerpods@if3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue state UNKNOWN group default 
    link/ether ba:47:d0:73:da:b9 brd ff:ff:ff:ff:ff:ff link-netnsid 0 promiscuity 0 allmulti 0 minmtu 68 maxmtu 65535 
    vxlan id 555000 remote 10.138.0.9 srcport 0 0 dstport 4790 ttl auto ageing 300 nolearning numtxqueues 1 numrxqueues 1 gso_max_size 65536 gso_max_segs 65535 tso_max_size 65536 tso_max_segs 65535 gro_max_size 65536 gso_ipv4_max_size 65536 gro_ipv4_max_size 65536 
    inet 10.84.0.9/24 brd 10.84.0.255 scope global vxlan-peerpods
       valid_lft forever preferred_lft forever
    inet6 fe80::b847:d0ff:fe73:dab9/64 scope link proto kernel_ll 
       valid_lft forever preferred_lft forever
5: veth2@if4: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether 8a:ca:98:5c:3f:c5 brd ff:ff:ff:ff:ff:ff link-netnsid 0 promiscuity 0 allmulti 0 minmtu 68 maxmtu 65535 
    veth numtxqueues 1 numrxqueues 1 gso_max_size 65536 gso_max_segs 65535 tso_max_size 524280 tso_max_segs 65535 gro_max_size 65536 gso_ipv4_max_size 65536 gro_ipv4_max_size 65536 
    inet6 fe80::88ca:98ff:fe5c:3fc5/64 scope link proto kernel_ll 
       valid_lft forever preferred_lft forever
```

Full agent-protocol-forwarder log:

https://paste.centos.org/view/4cc600f9

### PR DESCRIPTION
**Pull request by yoheiueda**
CNI plugins like PTP and GKE remove a route that is automatically added by kernel for eth0, and then add another route for the same destination.

This patch changes the code to manipulates routes to support such CNI plugins.

Fixes #1909

### CODE REVIEW

**Comment by yoheiueda** [comment]
I tested this PR with Flannel and Libvirt driver.

**Comment by beraldoleal** [comment]
Hi @yoheiueda thanks a lot. I just tested on GCP provider I'm cooking and it worked fine! While I'm not familiar with this part of the code, tomorrow I will do my best to review it.

File: src/cloud-api-adaptor/pkg/podnetwork/tunneler/routing/podnode.go [hunk 1]
```diff
@@ -39,6 +38,7 @@ func (t *podNodeTunneler) Setup(nsPath string, podNodeIPs []netip.Addr, config *
 		return errors.New("secondary pod node IP is not available")
 	}
 
+	podVEthName := config.InterfaceName
```
Comment (beraldoleal) [inline src/cloud-api-adaptor/pkg/podnetwork/tunneler/routing/podnode.go:41]: Have you considered the cases where `config.InterfaceName` is not defined? Should we have a default value? Or maybe a simpler approach for now where we check if `podVEthName` is valid the same way we are doing on line 47 for `hostNS`?

File: src/cloud-api-adaptor/pkg/podnetwork/tunneler/vxlan/podnode.go [hunk 2]
```diff
@@ -25,6 +24,7 @@ func NewPodNodeTunneler() tunneler.Tunneler {
 
 func (t *podNodeTunneler) Setup(nsPath string, podNodeIPs []netip.Addr, config *tunneler.Config) error {
 
+	podVxlanInterface := config.InterfaceName
```
Comment (beraldoleal) [inline src/cloud-api-adaptor/pkg/podnetwork/tunneler/vxlan/podnode.go:27]: Same here.

**Review by beraldoleal — COMMENTED** [review]
Hi @yoheiueda , this LGTM and as I mentioned before, its working with GKE.

Thank you a lot. Just left two minor comments for you.

File: src/cloud-api-adaptor/pkg/podnetwork/tunneler/routing/podnode.go (hunk 1 above)
Comment (yoheiueda) [reply src/cloud-api-adaptor/pkg/podnetwork/tunneler/routing/podnode.go:41]: Yes. we need an empty string check here. I'll add it.

File: src/cloud-api-adaptor/pkg/podnetwork/tunneler/vxlan/podnode.go (hunk 2 above)
Comment (yoheiueda) [reply src/cloud-api-adaptor/pkg/podnetwork/tunneler/vxlan/podnode.go:27]: We need an null string check here as well.

I noticed another issue here. podVxlanInterface is created in the host network interface first, and then it is move to the pod network namespace at Line 61 `vxlan.SetNamespace(podNS)`.

If podVxlanInterface is some common network interface name like eth0, then it may conflict with interfaces in the host network namespace. We may use a fixed non-common interface name for vxlan interface, and then we can rename it after it is moved to the pod network namespace.

I'll fix this issue.

File: src/cloud-api-adaptor/pkg/podnetwork/tunneler/routing/podnode.go (hunk 1 above)
Comment (yoheiueda) [reply src/cloud-api-adaptor/pkg/podnetwork/tunneler/routing/podnode.go:41]: done

File: src/cloud-api-adaptor/pkg/podnetwork/tunneler/vxlan/podnode.go (hunk 2 above)
Comment (yoheiueda) [reply src/cloud-api-adaptor/pkg/podnetwork/tunneler/vxlan/podnode.go:29]: done

**Review by beraldoleal — APPROVED** [review]
LGTM, thanks.

**Review by c3d — COMMENTED** [review]
I don't feel qualified to approve this code, but FWIW, looks good to me.

**Comment by bpradipt** [comment]
@yoheiueda I tried with docker provider on a kind cluster and pod creation fails with

```
/usr/local/bin/agent-protocol-forwarder: error running a service *forwarder.daemon: failed to set up pod network: failed to set up tunnel "vxlan": failed to add vxlan interface vxlan0: failed to create vxlan interface "vxlan0": /proc/1217/task/1220/ns/net:  file exists
agent-protocol-forwarder.service: Main process exited, code=exited, status=1/FAILURE
```

In case you want to try here are the images
- quay.io/bpradipt/cloud-api-adaptor:latest
- quay.io/bpradipt/podvm-docker-image

**Comment by EmmEff** [comment]
Would this resolve the issue usnig the EKS CNI driver as well?

**Comment by yoheiueda** [comment]
@bpradipt thank you for testing this PR.

The root cause of the issue is due to this error.

```
/usr/local/bin/agent-protocol-forwarder: error running a service *forwarder.daemon: failed to set up pod network: failed to remove route 172.16.246.53/32 dev eth0: failed to identify routes to be deleted: dest: 172.16.246.53/32, gw: invalid IP, dev eth0: %!w(<nil>)
```

Calico sets a Pod IP on an interface with prefix `/32`. In this case, Linux kernel does not automatically create a route for it.

I added a logic to handle this case, and tested it on docker with Calico as well as libvirt with flannel.

**Comment by yoheiueda** [comment]
@EmmEff

> Would this resolve the issue usnig the EKS CNI driver as well?

What kind of problems did you encounter with EKS CNI?

If this patch does not help for EKS CNI, please create another issue? I'll take a look at it.

**Comment by bpradipt** [comment]
@yoheiueda I tested with ovn-kubernetes on OpenShift as well and things looks good

```
$ RUN_TESTS=TestPodToServiceCommunicationAzure TEST_TRUSTEE_OPERATOR=yes TEST_PROVISION=no TEST_INSTALL_CAA=no make CLOUD_PROVIDER=azure TEST_PROVISION_FILE=$HOME/azure.properties test-e2e
go test -v -tags=azure -timeout 60m -count=1 -run TestPodToServiceCommunicationAzure ./test/e2e
time="2024-07-26T10:46:30+05:30" level=info msg="Do setup"
time="2024-07-26T10:46:30+05:30" level=info msg="Container runtime: crio"
time="2024-07-26T10:46:32+05:30" level=info msg="Creating namespace 'coco-pp-e2e-test-69bcc389'..."
time="2024-07-26T10:46:32+05:30" level=info msg="Wait for namespace 'coco-pp-e2e-test-69bcc389' be ready..."
time="2024-07-26T10:46:38+05:30" level=info msg="Wait for default serviceaccount in namespace 'coco-pp-e2e-test-69bcc389'..."
time="2024-07-26T10:46:38+05:30" level=info msg="default serviceAccount exists, namespace 'coco-pp-e2e-test-69bcc389' is ready for use"
=== RUN   TestPodToServiceCommunicationAzure
=== PAUSE TestPodToServiceCommunicationAzure
=== CONT  TestPodToServiceCommunicationAzure
=== RUN   TestPodToServiceCommunicationAzure/TestExtraPods_test
    assessment_runner.go:265: Waiting for containers in pod: nginx are ready
time="2024-07-26T10:48:24+05:30" level=info msg="webserver service is available on cluster IP: 172.30.135.42"
Provision extra pod busybox    assessment_helpers.go:425: Waiting for containers in pod: busybox are ready
=== RUN   TestPodToServiceCommunicationAzure/TestExtraPods_test/Failed_to_test_extra_pod.
time="2024-07-26T10:49:58+05:30" level=info msg="VM found in resource group"
time="2024-07-26T10:50:05+05:30" level=info msg="Success to access nginx service. <!DOCTYPE html>\n<html>\n<head>\n<title>Welcome to nginx!</title>\n<style>\nhtml { color-scheme: light dark; }\nbody { width: 35em; margin: 0 auto;\nfont-family: Tahoma, Verdana, Arial, sans-serif; }\n</style>\n</head>\n<body>\n<h1>Welcome to nginx!</h1>\n<p>If you see this page, the nginx web server is successfully installed and\nworking. Further configuration is required.</p>\n\n<p>For online documentation and support please refer to\n<a href=\"http://nginx.org/\">nginx.org</a>.<br/>\nCommercial support is available at\n<a href=\"http://nginx.com/\">nginx.com</a>.</p>\n\n<p><em>Thank you for using nginx.</em></p>\n</body>\n</html>\n"
    assessment_runner.go:517: Output when execute test commands:<!DOCTYPE html>
        <html>
        <head>
        <title>Welcome to nginx!</title>
        <style>
        html { color-scheme: light dark; }
        body { width: 35em; margin: 0 auto;
        font-family: Tahoma, Verdana, Arial, sans-serif; }
        </style>
        </head>
        <body>
        <h1>Welcome to nginx!</h1>
        <p>If you see this page, the nginx web server is successfully installed and
        working. Further configuration is required.</p>
        
        <p>For online documentation and support please refer to
        <a href="http://nginx.org/">nginx.org</a>.<br/>
        Commercial support is available at
        <a href="http://nginx.com/">nginx.com</a>.</p>
        
        <p><em>Thank you for using nginx.</em></p>
        </body>
        </html>
time="2024-07-26T10:50:06+05:30" level=info msg="VM found in resource group"
time="2024-07-26T10:50:06+05:30" level=info msg="Deleting pod nginx..."
time="2024-07-26T10:50:51+05:30" level=info msg="Pod nginx has been successfully deleted within 120s"
time="2024-07-26T10:50:52+05:30" level=info msg="Deleting pod busybox..."
time="2024-07-26T10:51:37+05:30" level=info msg="Pod busybox has been successfully deleted within 120s"
time="2024-07-26T10:51:37+05:30" level=info msg="Deleting Service... nginx"
--- PASS: TestPodToServiceCommunicationAzure (299.50s)
    --- PASS: TestPodToServiceCommunicationAzure/TestExtraPods_test (299.50s)
        --- PASS: TestPodToServiceCommunicationAzure/TestExtraPods_test/Failed_to_test_extra_pod. (11.06s)
PASS
time="2024-07-26T10:51:38+05:30" level=info msg="Deleting namespace 'coco-pp-e2e-test-69bcc389'..."
time="2024-07-26T10:51:48+05:30" level=info msg="Namespace 'coco-pp-e2e-test-69bcc389' has been successfully deleted within 60s"
ok      

$ RUN_TESTS=TestPodsMTLSCommunicationAzure TEST_TRUSTEE_OPERATOR=yes TEST_PROVISION=no TEST_INSTALL_CAA=no make CLOUD_PROVIDER=azure TEST_PROVISION_FILE=$HOME/azure.properties test-e2e 
go test -v -tags=azure -timeout 60m -count=1 -run TestPodsMTLSCommunicationAzure ./test/e2e
time="2024-07-26T10:53:40+05:30" level=info msg="Do setup"
time="2024-07-26T10:53:40+05:30" level=info msg="Container runtime: crio"
time="2024-07-26T10:53:42+05:30" level=info msg="Creating namespace 'coco-pp-e2e-test-633d86dd'..."
time="2024-07-26T10:53:42+05:30" level=info msg="Wait for namespace 'coco-pp-e2e-test-633d86dd' be ready..."
time="2024-07-26T10:53:47+05:30" level=info msg="Wait for default serviceaccount in namespace 'coco-pp-e2e-test-633d86dd'..."
time="2024-07-26T10:53:48+05:30" level=info msg="default serviceAccount exists, namespace 'coco-pp-e2e-test-633d86dd' is ready for use"
=== RUN   TestPodsMTLSCommunicationAzure
=== PAUSE TestPodsMTLSCommunicationAzure
=== CONT  TestPodsMTLSCommunicationAzure
=== RUN   TestPodsMTLSCommunicationAzure/TestPodsMTLSCommunication_test
    assessment_runner.go:265: Waiting for containers in pod: nginx are ready
time="2024-07-26T10:55:30+05:30" level=info msg="webserver service is available on cluster IP: 172.30.8.170"
Provision extra pod curl    assessment_helpers.go:425: Waiting for containers in pod: curl are ready
=== RUN   TestPodsMTLSCommunicationAzure/TestPodsMTLSCommunication_test/Pods_communication_with_mTLS
time="2024-07-26T10:56:59+05:30" level=info msg="VM found in resource group"
time="2024-07-26T10:57:07+05:30" level=info msg="Success to access nginx service. <!DOCTYPE html>\n<html>\n<head>\n<title>Welcome to nginx!</title>\n<style>\nhtml { color-scheme: light dark; }\nbody { width: 35em; margin: 0 auto;\nfont-family: Tahoma, Verdana, Arial, sans-serif; }\n</style>\n</head>\n<body>\n<h1>Welcome to nginx!</h1>\n<p>If you see this page, the nginx web server is successfully installed and\nworking. Further configuration is required.</p>\n\n<p>For online documentation and support please refer to\n<a href=\"http://nginx.org/\">nginx.org</a>.<br/>\nCommercial support is available at\n<a href=\"http://nginx.com/\">nginx.com</a>.</p>\n\n<p><em>Thank you for using nginx.</em></p>\n</body>\n</html>\n"
    assessment_runner.go:517: Output when execute test commands:<!DOCTYPE html>
        <html>
        <head>
        <title>Welcome to nginx!</title>
        <style>
        html { color-scheme: light dark; }
        body { width: 35em; margin: 0 auto;
        font-family: Tahoma, Verdana, Arial, sans-serif; }
        </style>
        </head>
        <body>
        <h1>Welcome to nginx!</h1>
        <p>If you see this page, the nginx web server is successfully installed and
        working. Further configuration is required.</p>
        
        <p>For online documentation and support please refer to
        <a href="http://nginx.org/">nginx.org</a>.<br/>
        Commercial support is available at
        <a href="http://nginx.com/">nginx.com</a>.</p>
        
        <p><em>Thank you for using nginx.</em></p>
        </body>
        </html>
time="2024-07-26T10:57:07+05:30" level=info msg="VM found in resource group"
time="2024-07-26T10:57:07+05:30" level=info msg="Deleting Configmap... nginx-conf"
time="2024-07-26T10:57:08+05:30" level=info msg="Deleting Secret... server-certs"
time="2024-07-26T10:57:08+05:30" level=info msg="Deleting extra Secret... curl-certs"
time="2024-07-26T10:57:08+05:30" level=info msg="Deleting pod nginx..."
time="2024-07-26T10:57:53+05:30" level=info msg="Pod nginx has been successfully deleted within 120s"
time="2024-07-26T10:57:53+05:30" level=info msg="Deleting pod curl..."
time="2024-07-26T10:58:39+05:30" level=info msg="Pod curl has been successfully deleted within 120s"
time="2024-07-26T10:58:39+05:30" level=info msg="Deleting Service... nginx"
--- PASS: TestPodsMTLSCommunicationAzure (291.26s)
    --- PASS: TestPodsMTLSCommunicationAzure/TestPodsMTLSCommunication_test (291.26s)
        --- PASS: TestPodsMTLSCommunicationAzure/TestPodsMTLSCommunication_test/Pods_communication_with_mTLS (11.16s)
PASS
time="2024-07-26T10:58:39+05:30" level=info msg="Deleting namespace 'coco-pp-e2e-test-633d86dd'..."
time="2024-07-26T10:58:50+05:30" level=info msg="Namespace 'coco-pp-e2e-test-633d86dd' has been successfully deleted within 60s"
ok      github.com/confidential-containers/cloud-api-adaptor/src/cloud-api-adaptor/test/e2e     311.573s


$ RUN_TESTS=TestPodToDownloadExternalFileAzure  TEST_TRUSTEE_OPERATOR=yes TEST_PROVISION=no TEST_INSTALL_CAA=no make CLOUD_PROVIDER=azure TEST_PROVISION_FILE=$HOME/azure.properties test-e2e 
go test -v -tags=azure -timeout 60m -count=1 -run TestPodToDownloadExternalFileAzure ./test/e2e
time="2024-07-26T11:10:54+05:30" level=info msg="Do setup"
time="2024-07-26T11:10:54+05:30" level=info msg="Container runtime: crio"
time="2024-07-26T11:10:56+05:30" level=info msg="Creating namespace 'coco-pp-e2e-test-0924345a'..."
time="2024-07-26T11:10:56+05:30" level=info msg="Wait for namespace 'coco-pp-e2e-test-0924345a' be ready..."
time="2024-07-26T11:11:01+05:30" level=info msg="Wait for default serviceaccount in namespace 'coco-pp-e2e-test-0924345a'..."
time="2024-07-26T11:11:02+05:30" level=info msg="default serviceAccount exists, namespace 'coco-pp-e2e-test-0924345a' is ready for use"
=== RUN   TestPodToDownloadExternalFileAzure
=== PAUSE TestPodToDownloadExternalFileAzure
=== CONT  TestPodToDownloadExternalFileAzure
=== RUN   TestPodToDownloadExternalFileAzure/PodWithSpecificCommands_test
    assessment_runner.go:265: Waiting for containers in pod: simple-test are ready
=== RUN   TestPodToDownloadExternalFileAzure/PodWithSpecificCommands_test/Pod_with_specific_commands
    assessment_runner.go:416: Output when execute test commands:
time="2024-07-26T11:12:42+05:30" level=info msg="VM found in resource group"
time="2024-07-26T11:12:42+05:30" level=info msg="Deleting pod simple-test..."
time="2024-07-26T11:13:28+05:30" level=info msg="Pod simple-test has been successfully deleted within 120s"
--- PASS: TestPodToDownloadExternalFileAzure (145.80s)
    --- PASS: TestPodToDownloadExternalFileAzure/PodWithSpecificCommands_test (145.80s)
        --- PASS: TestPodToDownloadExternalFileAzure/PodWithSpecificCommands_test/Pod_with_specific_commands (9.50s)
PASS
time="2024-07-26T11:13:28+05:30" level=info msg="Deleting namespace 'coco-pp-e2e-test-0924345a'..."
time="2024-07-26T11:13:38+05:30" level=info msg="Namespace 'coco-pp-e2e-test-0924345a' has been successfully deleted within 60s"
ok      github.com/confidential-containers/cloud-api-adaptor/src/cloud-api-adaptor/test/e2e     166.471s
```

**Review by bpradipt — APPROVED** [review]
/lgtm

**Comment by bpradipt** [comment]
@stevenhorsman based on the tests carried till now, this PR should be ok to merge.
Would leave it to you to take the final call :-)

**Comment by bpradipt** [comment]
> @EmmEff
> 
> > Would this resolve the issue usnig the EKS CNI driver as well?
> 
> What kind of problems did you encounter with EKS CNI?
> 
> If this patch does not help for EKS CNI, please create another issue? I'll take a look at it.

@EmmEff this patch doesn't solve the external network connectivity issue with default EKS CNI.  I tested this on my setup and the external network connectivity problem remains with EKS CNI.

**Comment by EmmEff** [comment]
> @EmmEff
> 
> > Would this resolve the issue usnig the EKS CNI driver as well?
> 
> What kind of problems did you encounter with EKS CNI?
> 
> If this patch does not help for EKS CNI, please create another issue? I'll take a look at it.

Admittedly I am not entirely sure of the cause of the connectivity issue with the EKS CNI. At a high level, there is no network connectivity from the pod running in the CVM to the outside. Maybe @bpradipt can better explain?

**Comment by yoheiueda** [comment]
@beraldoleal @EmmEff 
I raised an issue for EKS. Let's continue discussion there.
https://github.com/confidential-containers/cloud-api-adaptor/issues/1966
