### PR TITLE
Correct pod names reported by cri-o

### LINKED ISSUE #261: cri-o can't create a peer pod VM on IBM Cloud
When `cri-o` is used in IBM Cloud, `cloud-api-adaptor` fails to create a peer pod VM with the following error message.

```
2022/09/29 05:39:07 [helper/hypervisor] failed to create an instance : Invalid json payload provided and the response is {
```

```
            {
                "code": "bad_field",
                "message": "Invalid json payload provided",
                "target": {
                    "name": "name",
                    "type": "field"
                }
            }
```

This is due to a too long VM name specifed in CreateInstanceOptions.
https://github.com/confidential-containers/cloud-api-adaptor/blob/b369f91d72c44a0e12fb48144478efe669c33e5d/pkg/adaptor/hypervisor/ibmcloud/service.go#L155

### PR DESCRIPTION
**Pull request by yoheiueda**
cri-o reports sandbox names in the different format than containerd.

This patch corrects pod names reported by cri-o so that they are consistent with containerd.

Fixes #261

### CODE REVIEW

File: pkg/adaptor/hypervisor/aws/service.go [hunk 1]
```diff
@@ -104,6 +104,12 @@ func (s *hypervisorService) CreateVM(ctx context.Context, req *pb.CreateVMReques
 	if pod == "" {
 		return nil, fmt.Errorf("pod name %s is missing in annotations", annotations.SandboxName)
 	}
+	// cri-o stores the sandbox name in the form of k8s_<pod name>_<namespace>_<uid>_0
+	// Extract the pod name from it.
+	if tmp := strings.Split(pod, "_"); len(tmp) > 1 && tmp[0] == "k8s" {
+		pod = tmp[1]
+	}
+
```
Comment (bpradipt) [inline pkg/adaptor/hypervisor/aws/service.go:112]: @yoheiueda possible to put this snippet in the utils package?

Comment (yoheiueda) [reply pkg/adaptor/hypervisor/aws/service.go:108]: I updated the code. Could you review again?

File: pkg/adaptor/hypervisor/libvirt/service.go [hunk 2]
```diff
@@ -96,11 +97,12 @@ func (s *hypervisorService) CreateVM(ctx context.Context, req *pb.CreateVMReques
 	if _, exists := s.sandboxes[sid]; exists {
 		return nil, fmt.Errorf("sandbox %s already exists", sid)
 	}
-	pod := req.Annotations[annotations.SandboxName]
+	pod := hvutil.GetPodNamespace(req.Annotations)
```
Comment (littlejawa) [inline pkg/adaptor/hypervisor/libvirt/service.go:100]: I think here it should be "GetPodName", not "GetPodNamespace" ?

File: pkg/adaptor/hypervisor/vsphere/service.go [hunk 3]
```diff
@@ -97,11 +98,12 @@ func (s *hypervisorService) CreateVM(ctx context.Context, req *pb.CreateVMReques
 	if _, exists := s.sandboxes[sid]; exists {
 		return nil, fmt.Errorf("sandbox %s already exists", sid)
 	}
-	pod := req.Annotations[annotations.SandboxName]
+	pod := hvutil.GetPodNamespace(req.Annotations)
```
Comment (littlejawa) [inline pkg/adaptor/hypervisor/vsphere/service.go:101]: Same ?

Comment (yoheiueda) [reply pkg/adaptor/hypervisor/vsphere/service.go:101]: oh, sorry. I'll fix it.

Comment (yoheiueda) [reply pkg/adaptor/hypervisor/vsphere/service.go]: done

File: pkg/adaptor/hypervisor/libvirt/service.go (hunk 2 above)
Comment (yoheiueda) [reply pkg/adaptor/hypervisor/libvirt/service.go]: fixed

**Comment by yoheiueda** [comment]
I moved the `pkg/adaptor/hypervisor/hvutil` to `pkg/util/hvutil`.

**Review by bpradipt — APPROVED** [review]
/lgtm
Thanks @yoheiueda
